title: Engineering Blog

collections:
   notes:
    output: true


plugins:
   - jekyll-feed
   - jekyll-sitemap
   - jekyll-seo-tag
   - jekyll-paginate

paginate: 5


defaults:
  - scope:
      path: ""
      type: "notes"
    values: 
      layout: "note"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
