title: Engineering Blog

collections:
   notes:
    output: true


plugins:
   - jekyll-feed
   - jekyll-sitemap
   - jekyll-seo-tag
   - jekyll-paginate

paginate: 10
paginate_path: /page:num/